INSERT INTO APP_ROLE (CODE, DESC) VALUES ('ROLE_ADMIN', 'Administrator');
INSERT INTO APP_ROLE (CODE, DESC) VALUES ('ROLE_APPLIER', 'Applier');
INSERT INTO APP_ROLE (CODE, DESC) VALUES ('ROLE_CONFIRMER', 'Confirmer');
INSERT INTO APP_ROLE (CODE, DESC) VALUES ('ROLE_HR', 'HR');
