INSERT INTO APP_USER_ROLE (OID, USER_ACCOUNT, ROLE_ID) VALUES (REPLACE(RANDOM_UUID(), '-'), 'user2', 2);
INSERT INTO APP_USER_ROLE (OID, USER_ACCOUNT, ROLE_ID) VALUES (REPLACE(RANDOM_UUID(), '-'), 'user21', 2);
INSERT INTO APP_USER_ROLE (OID, USER_ACCOUNT, ROLE_ID) VALUES (REPLACE(RANDOM_UUID(), '-'), 'user3', 3);
INSERT INTO APP_USER_ROLE (OID, USER_ACCOUNT, ROLE_ID) VALUES (REPLACE(RANDOM_UUID(), '-'), 'user4', 4);