DROP TABLE IF EXISTS APP_FUNCTION;

CREATE TABLE APP_FUNCTION (
    ID         BIGINT NOT NULL AUTO_INCREMENT COMMENT '功能編號',
    PARENT     VARCHAR(10) NOT NULL COMMENT '父功能代碼',
    CODE       VARCHAR(10) NOT NULL COMMENT '功能代碼',
    LEVEL      INT NOT NULL DEFAULT 1 COMMENT '功能階層',
    NAME       VARCHAR(10) NOT NULL COMMENT '功能名稱',
    ICON       VARCHAR(50) COMMENT '功能圖示',
    PATH       VARCHAR(100) NOT NULL DEFAULT NULL COMMENT '功能路徑',
    CONSTRAINT APP_FUNCTION_PK PRIMARY KEY (ID),
    UNIQUE INDEX APP_FUNCTION_UNIQUE (NAME ASC)
);
