DROP TABLE IF EXISTS APP_ROLE;

CREATE TABLE APP_ROLE (
    ID     BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色編號',
    CODE   VARCHAR(45) DEFAULT NULL COMMENT '角色代碼',
    DESC   VARCHAR(200) DEFAULT NULL COMMENT '角色敘述',
    CONSTRAINT APP_ROLE_PK PRIMARY KEY (ID),
    UNIQUE INDEX APP_ROLE_UNIQUE (CODE ASC)
);