DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
    ID       BIGINT AUTO_INCREMENT NOT NULL COMMENT '使用者編號',
    ACCOUNT  VARCHAR(50) NOT NULL COMMENT '使用者帳號',
    NAME     VARCHAR(45) NOT NULL COMMENT '使用者姓名',
    EMAIL    VARCHAR(200) NOT NULL COMMENT '使用者信箱',
    STATUS   VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '使用者狀態',
    LAST_LOGIN_DT DATETIME NULL DEFAULT NULL COMMENT '上次登入時間',
    CONSTRAINT APP_USER_PK PRIMARY KEY (ID),
    UNIQUE INDEX APP_USER_UNIQUE (ACCOUNT ASC)
);