DROP TABLE IF EXISTS CASE_ID;

CREATE TABLE CASE_ID (
    DEPT_CAT varchar(32) NOT NULL COMMENT '部門代碼',
    CASE_DATE date NOT NULL COMMENT '案件日期',
    CASE_SEQUENCE bigint(20) DEFAULT NULL COMMENT '案件流水號',
    CASE_SEQ_COUNT int(11) DEFAULT NULL COMMENT '案件流水號長度',
    UPDATE_TIME datetime NULL COMMENT '最後修改時間',
    CONSTRAINT CASE_ID_PK PRIMARY KEY (DEPT_CAT)
);