DROP TABLE IF EXISTS CASE_DETAIL;

CREATE TABLE CASE_DETAIL (
    DETAIL_ID BIGINT AUTO_INCREMENT NOT NULL COMMENT '訊息編號',
    CASE_ID BIGINT NOT NULL COMMENT '案件編號',
    CASE_STATUS VARCHAR(3) NOT NULL COMMENT '案件狀態',
    MSG_DETAIL TEXT COMMENT '訊息內容',
    UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新時間',

    CONSTRAINT CASE_DETAIL_PK PRIMARY KEY (DETAIL_ID),
    CONSTRAINT CASE_DETAIL_FK FOREIGN KEY (CASE_ID) REFERENCES CASE_MAIN (CASE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
